spring:
  application:
    name: repo-backend-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: rag-service
            uri: ${RAG_SERVICE_URL:http://localhost:8082}
            predicates:
              - Path=/api/node/**
            filters:
              - StripPrefix=2

          - id: repo-backend-core-service
            uri: ${CORE_SERVICE_URL:http://localhost:8081}
            predicates:
              - Path=/api/spring/**
            filters:
              - StripPrefix=2

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
