spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: rag-service
            uri: http://localhost:3000
            predicates:
              - Path=/api/node/**
            filters:
              - StripPrefix=2

          - id: spring-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/spring/**
            filters:
              - StripPrefix=2

server:
  port: 8080
